### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by sudhirj** [lakshmananmurugesan/distributor_problem#1]
There's an error on this line:

https://github.com/lakshmananmurugesan/distributor_problem/blob/master/helper.rb#L47

Is this valid ruby at all?

**Comment by lakshmananmurugesan** [comment]
@sudhirj  The code at 47 is valid ruby and it works for my sample inputs. I hope you have reviewed the screenshots (Sample input and output) attached in the email. 

Can you please share input and output or scenario when it is throwing error?

**Comment by sudhirj** [comment]
Okay, will try with 1.8 and 1.9. Are you using Ruby 2.x or 1.x?

**Comment by lakshmananmurugesan** [comment]
@sudhirj The Ruby version used is 2.2.2

**Comment by lakshmananmurugesan** [comment]
@sudhirj Good afternoon, I hope you have received the code updates email to your gmail account. I too informed this to Sriram. Currently, I have updated the existing solution to work with multiple address format with input as comma separated. I am just thinking to improve the handling of input from ,,Queensown,,Singapore to Queenstown,Singapore.
